### ISSUE TITLE
wrong placement in marble nest

### ISSUE THREAD

**Issue by zerozakialayashiki** [pathologicdialogue/pathologicdialogue.github.io#3]
There are several misplacement of dialogues in marble nest.
Like the second marat dialogue, session 1, the first "10" should end to the dialogue, but it continues in the project.
There are several other examples I have found, but since I didn't note them down I cannot report for now.
I may post more here if I found more misplacement.
Also the marble nest one seems to have some dialogues not included, I haven't test in game but I found those dialogues in the file, not sure if they are unused.

**Comment by zerozakialayashiki** [comment]
It is "12" instead of "10", sorry.
This one, more precisely:
"I'm sorry, but I can't just let you die. If you're infected, I need to keep you here as proof that I'm" (the rest is omitted)

**Comment by pathologicdialogue** [comment]
Everything is compiled programmatically based on the game files. Sometimes certain dialogues depend on the external events, in those cases the thread might end up being split off. Don't think I would be able to fix this without manually going through every single line, and it's a bit too much for me, although if someone ambitious wants to do it, I'd be happy to incorporate their edits

**Comment by zerozakialayashiki** [comment]
Got it.
I still hope that you could add a description or something which states the dialogue archive being not 100% correct. 
Thank you for your effort, the project is really helpful (I am making a fan translation of the second game).

**Comment by TR-221** [comment]
```
Marat Ranin: [The symptoms do remind you of the sand plague: fever, dilated pupils, slurred speech patterns. He will not live to see this evening. But a person sick with sand plague at this stage would also have yellowish skin coloration. It's hard to say for sure.]
	[R1] Bachelor: I'm sorry, but I can't just let you die. If you're infected, I need to keep you here as proof that I'm right about the new outbreak. I'm locking you in.
		Marat Ranin: Dora wouldn't leave without me. You have to find a way to trick her. Tell her I'm okay.She doesn't belong here.
			Bachelor: ...To hell with you two. Get lost, both of you.I hope I won't come to regret this decision.
			Bachelor: Her choice. That means you both are staying.
	[R2] Bachelor: ...Say what you will, but it's not the sand pest. I'd say euthanasia by soldiers' bullets is inadvisable in your case. You will be escorted to my place. I'll take another look at you in the evening.
		Marat Ranin: (the dialogue goes on...)
	[R3] Bachelor: I'm sorry, but I can't just let you die. If you're infected, I need to keep you here as proof that I'm right about the new outbreak. I'm locking you in.
```
While this discussion is closed, I would like to add a more technical explanation of how this work. You can notice that "I'm sorry, but I can't just let you..." appears twice in this situation, one continuing the dialogue, the other ending it. These are actually two different lines in the game file with separate IDs. _R1 (reply 1)_ is _6192355001840919_; in _reply.xml_ this line has _index 0_ (it appears at the top) and an `<EnableCondition>1688824095003451</EnableCondition>` tag (which is required for it to appear), the string in which in _conditions.xml_ corresponds to _"DoraFree". R3 (reply 3)_ is _6192355001983151_, with _index 2_ (it appears at the bottom) and `<EnableCondition>1688824095003453</EnableCondition>` tag, which leads to _"DoraNotFree"_.
Basically what this means is that we have two separate lines and which one we see depends on the condition being met. If we talk to Marat first, or Dora, but decide not to let her go, then we will see _R3 (6192355001983151)_, which ends the dialogue; if we talk to Dora first and decide to let her go, then we will see _R1 (6192355001840919)_. A similar situation exists in the dialogue with Dora: there are two similar replies under different IDs, which have conditions to be met in order to be seen; if Marat is free, the line that continues the dialogue is used, if not, the line that ends the dialogue is used.

I think this could be solved by checking for `<EnableCondition></EnableCondition>', and if it appears within the reply element, cross-check it with conditions.xml and append name from the <Name></Name> tag somewhere; either before or after the response, like this:

```
Marat Ranin: [The symptoms do remind you of the sand plague: fever, dilated pupils, slurred speech patterns. He will not live to see this evening. But a person sick with sand plague at this stage would also have yellowish skin coloration. It's hard to say for sure.]
	[R1] Bachelor: I'm sorry, but I can't just let you die. If you're infected, I need to keep you here as proof that I'm right about the new outbreak. I'm locking you in. (CONDITION: DoraFree)
	[R2] Bachelor: ...Say what you will, but it's not the sand pest. I'd say euthanasia by soldiers' bullets is inadvisable in your case. You will be escorted to my place. I'll take another look at you in the evening.
	[R3] Bachelor: I'm sorry, but I can't just let you die. If you're infected, I need to keep you here as proof that I'm right about the new outbreak. I'm locking you in. (CONDITION: DoraNotFree)
```
